{"email": ["drgenarovazquez@gmail.com"]}
{"email": ["sonelle74@hotmail.com"]}
{"email": ["maxjulio@prodigy.net.mx"]}
{"email": ["gerardoblancov@hotmail.com"]}
{"email": ["rcarmonas1@prodigy.net.mx"]}
{"email": ["plpardo@hotmail.com"]}
{"email": ["investigacionhgam@gmail.com"]}
{"email": ["aldolasa@hotmail.com"]}
{"email": ["moy1510@hotmail.com"]}
{"email": ["andresgomezmd@hotmail.com"]}
{"email": ["miguelvaldovinosd@gmail.com"]}
{"email": ["centro_investigacion_ehg@hotmail.com"]}
{"email": ["kazuofurusho@hotmail.com"]}
{"email": ["o.munoz@javeriana.edu.co"]}
{"email": ["pbl.weber@hotmail.com"]}
{"email": ["solistellez@hotmail.com"]}
{"email": ["lopez_colombo@yahoo.com"]}
{"email": ["gabrielarismendi@gmail.com"]}
{"email": ["grubejr78@gmail.com"]}
{"email": ["joctavioalonso@yahoo.com.mx"]}
{"email": ["arantesvitor@hotmail.com"]}
{"email": ["ssobrinocossio@gmail.com"]}
{"email": ["goizalnaz@gmail.com"]}
{"email": ["gabycarloscris@yahoo.es"]}
{"email": ["davidruizcla@gmail.com"]}
{"email": ["jsanchez@dgepi.salud.gob.mx"]}
{"email": ["AFrati@alfawassermann.com", "afratim@hotmail.com"]}
{"email": ["urossi76@hotmail.com"]}
{"email": ["brisar1cg@hotmail.com"]}
{"email": ["gerardoblancor@yahoo.com.mx"]}
{"email": ["membriale@yahoo.com.mx"]}
{"email": ["malopez0305@yahoo.com.mx"]}
{"email": ["mvallejosoto@gmail.com"]}
{"email": ["plonecef@gmail.com"]}
{"email": ["benetsergio@gmail.com"]}
{"email": ["gregareag@gmail.com"]}
{"email": ["ladan.hulp@salud.madrid.org"]}
{"email": ["maguidi71@yahoo.com.ar"]}
{"email": ["aliciaruiz9@hotmail.com"]}
{"email": ["aleix.martinez.perez@gmail.com"]}
{"email": ["jgonzalomendez82@gmail.com"]}
{"email": ["ruby_derma@hotmail.com"]}
{"email": ["carlossalceda@yahoo.com"]}
{"email": ["rcarmonas1@prodigy.net.mx"]}
{"email": ["aldo.montano-loza@ualberta.ca"]}
{"email": ["gastroconsulta@gmail.com"]}
{"email": ["sgiono@yahoo.com"]}
{"email": ["lcendosrocha@gmail.com"]}
{"email": ["rcarmonas1@prodigy.net.mx"]}
{"email": ["carlosbenjamings@hotmail.com"]}
{"email": ["sofiarj13@hotmail.com"]}
{"email": ["jlberistain@yahoo.com"]}
{"email": ["afrati@alfawassermann.com"]}
{"email": ["jose.remes.troche@gmail.com"]}
{"email": ["gabrielarismendi@gmail.com"]}
{"email": ["medicina.guerra@gmail.com"]}
{"email": ["urossi76@hotmail.com"]}
{"email": ["anaggparedes@gmail.com"]}
{"email": ["ruby_derma@hotmail.com"]}
{"email": ["rcarmonas1@prodigy.net.mx"]}
{"email": ["badir84@hotmail.com"]}
{"email": ["fab_romanom@hotmail.com"]}
{"email": ["rcarmonas1@prodigy.net.mx"]}
{"email": ["luis.uscangad@gmail.com"]}
{"email": ["drjuanmiguelabdo@yahoo.com.mx"]}
{"email": ["vfparrap@yahoo.es"]}
{"email": ["aparradelriego@gmail.com"]}
{"email": ["digarciacompean@prodigy.net.mx"]}
{"email": ["cecicurvale@hotmail.com"]}
{"email": ["maxjulio@prodigy.net.mx"]}
{"email": ["pcaden60@hotmail.com"]}
{"email": ["karmirandabarbachano@gmail.com"]}
{"email": ["joctavioalonso@yahoo.com.mx"]}
{"email": ["mario_eta13@hotmail.com"]}
{"email": ["othoncruz@yahoo.com"]}
{"email": ["urossi76@hotmail.com"]}
{"email": ["cecicurvale@hotmail.com"]}
{"email": ["urossi76@hotmail.com"]}
{"email": ["lgdominguez@hotmail.com"]}
{"email": ["es18497@gmail.com"]}
{"email": ["kazuofurusho@hotmail.com"]}
{"email": ["fabio_k111@hotmail.com"]}
{"email": ["urossi76@hotmail.com"]}
{"email": ["judith.mezajunco@albertahealthservices.ca"]}
{"email": ["kazuofurusho@hotmail.com"]}
{"email": ["moy1510@hotmail.com"]}
{"email": ["christian.mejia.md@gmail.com"]}
{"email": ["ulisesromed@prodigy.net.mx"]}
{"email": ["psharma@kumc.edu"]}
{"email": ["jsanchez@dgepi.salud.gob.mx"]}
{"email": ["tomas_miranda_a@hotmail.com"]}
{"email": ["monikazs@hotmail.com"]}
{"email": ["moy1510@hotmail.com"]}
{"email": ["lgdominguez@hotmail.com"]}
{"email": ["fhuertaiga@gmail.com"]}
{"email": ["leonardoabustamante@gmail.com"]}
{"email": ["gmtzmier@gmail.com"]}
{"email": ["silvia_pt_72@hotmail.com"]}
{"email": ["jalbertogastro@gmail.com"]}
{"email": ["dralejandromontano@hotmail.com"]}
{"email": ["mstoopen@ctscanner.mx"]}
{"email": ["jariant@hotmail.com"]}
{"email": ["centro_investigacion_ehg@hotmail.com"]}
{"email": ["Miguel.Saps@nationwidechildrens.org"]}
{"email": ["maballamo@yahoo.com"]}
{"email": ["rhonda.souza@verizon.net"]}
{"email": ["etavio@gmail.com"]}
{"email": ["drlaa@prodigy.net.mx"]}
{"email": ["m3lbita@hotmail.com"]}
{"email": ["detoal@yahoo.com"]}
{"email": ["sofiarj13@hotmail.com"]}
{"email": ["andres_gonzalez_garcia@hotmail.com"]}
{"email": ["ekimura@ctscanner.mx"]}
{"email": ["juarezmarco88@hotmail.com"]}
{"email": ["lapcolon@gmail.com"]}
{"email": ["deniskar@yahoo.com"]}
{"email": ["vfparrap@yahoo.es"]}
{"email": ["blancasoropeza@prodigy.net.mx"]}
{"email": ["fernandezerro@gmail.com"]}
{"email": ["pcalerogarcia@medicos.com"]}
{"email": ["radheyadqg@hotmail.com"]}
{"email": ["drhomerorodriguez@gmail.com"]}
{"email": ["rulosofo@gmail.com"]}
{"email": ["gabgurey@yahoo.com.mx"]}
{"email": ["maxjulio@prodigy.net.mx"]}
{"email": ["carlosvalenzuelas@gmail.com"]}
{"email": ["cmuneton@gmail.com"]}
{"email": ["epdch@hotmail.com"]}
{"email": ["Xavier.llor@yale.edu"]}
{"email": ["jmar001@hotmail.com"]}
{"email": ["fersi17@yahoo.com", "jennifer.forerop@gmail.com"]}
{"email": ["fitocuendis@hotmail.com"]}
{"email": ["angelgj83@gmail.com"]}
{"email": ["maxjulio@prodigy.net.mx"]}
{"email": ["morelosadolfo@hotmail.com"]}
{"email": ["drjuanslasa@gmail.com"]}
{"email": ["herimd@hotmail.com"]}
{"email": ["mondragonmd@yahoo.co.uk"]}
{"email": ["mondragonmd@yahoo.co.uk"]}
{"email": ["pbdemelo@hotmail.com"]}
{"email": ["grobertoguevara@gmail.com"]}
{"email": ["rodrigosotomd@hotmail.com"]}
{"email": ["katerina_klimova@yahoo.com"]}
{"email": ["maxjulio@prodigy.net.mx"]}
{"email": ["josegarcia_mex@hotmail.com"]}
{"email": ["agmarin1980@gmail.com"]}
{"email": ["jacquiemex2@yahoo.com.mx"]}
{"email": ["c_i_b_v@hotmail.com"]}
{"email": ["aleix.martinez.perez@gmail.com"]}
{"email": ["drinter77@gmail.com"]}
{"email": ["ruiznavas@hotmail.com"]}
{"email": ["elisaplus@yahoo.com.mx"]}
{"email": ["joremes@uv.mx"]}
{"email": ["eduardofloresv@gmail.com"]}
{"email": ["Ron.Schey@tuhs.temple.edu"]}
{"email": ["braulioaaroncc@hotmail.com"]}
{"email": ["bealvcue@gmail.com"]}
{"email": ["miguel.saps@nationwidechildrens.org"]}
{"email": ["sonelle74@hotmail.com"]}
{"email": ["maxjulio@prodigy.net.mx"]}
{"email": ["montanol@ualberta.ca"]}
{"email": ["detoal@yahoo.com"]}
{"email": ["sanguinetti.josema@gmail.com"]}
{"email": ["drdltorre@gmail.com"]}
{"email": ["Ron.Schey@tuhs.temple.edu"]}
{"email": ["amc@ciad.mx"]}
{"email": ["emtoromonjaraz@gmail.com"]}
{"email": ["nayelixoortiz@yahoo.com.mx"]}
{"email": ["riversidercg@hotmail.com"]}
{"email": ["geriaclinsecretaria@gmail.com"]}
{"email": ["pcaden60@hotmail.com"]}
{"email": ["jldominguezjim@hotmail.com"]}
{"email": ["dra_martinezgastro@hotmail.com"]}
{"email": ["emtoromonjaraz@hotmail.com"]}
{"email": ["rovaf@yahoo.com"]}
{"email": ["paulinomhm@hotmail.com"]}
{"email": ["enriquecossmd@gmail.com"]}
{"email": ["maxjulio@prodigy.net.mx"]}
{"email": ["jose.remes.troche@gmail.com"]}
{"email": ["carlossalceda@yahoo.com"]}
{"email": ["ramirez.ramirez.ma@gmail.com"]}
{"email": ["paulinomhm@hotmail.com"]}
{"email": ["cher_zilahy@hotmail.com"]}
{"email": ["esfenoides12@hotmail.com"]}
{"email": ["amh@hepatologia.org.mx"]}
{"email": ["florazarate@gmail.com"]}
{"email": ["martinez.gustavo@transplantver.com"]}
{"email": ["doctornares@hotmail.com"]}
{"email": ["maxjulio@prodigy.net.mx"]}
{"email": ["alainscequera@yahoo.com.mx"]}
{"email": ["cbuiles@hptu.org.co"]}
{"email": ["gferti@hotmail.com"]}
{"email": ["detoal@yahoo.com"]}
{"email": ["cabrera_md@icloud.com"]}
{"email": ["martinez.gustavo@transplantver.com.mx"]}
{"email": ["mvilatoba@hotmail.com"]}
{"email": ["jacovelazquez@gmail.com"]}
{"email": ["mariopl@prodigy.net.mx"]}
{"email": ["juanselasa@gmail.com"]}
{"email": ["aduarterojo@uams.edu"]}
{"email": ["laura_9487@yahoo.es"]}
{"email": ["endozaragoza_issste@yahoo.com.mx"]}
{"email": ["esther_garcia_santos@hotmail.com"]}
{"email": ["anasanunes@gmail.com"]}
{"email": ["aldoluyo@gmail.com"]}
{"email": ["quetzi80@yahoo.com"]}
{"email": ["danelyvaldovinos@hotmail.com"]}
{"email": ["emtoromonjaraz@hotmail.com"]}
{"email": ["mariopl@prodigy.net.mx"]}
{"email": ["andreaparrab@gmail.com"]}
{"email": ["mariopl@prodigy.net.mx"]}
{"email": ["jorgedafonseca@hotmail.com"]}
{"email": ["maruicaza@gmail.com"]}
{"email": ["fhuertaiga@prodigy.net.mx"]}
{"email": ["radheyadqg@gmail.com"]}
{"email": ["carlosfortea@gmail.com"]}
{"email": ["nsotelo51@gmail.com"]}
{"email": ["anamariamadrid@gmail.com"]}
{"email": ["rubiotapia.alberto@mayo.edu"]}
